# Generated by Django 4.1.3 on 2023-01-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
