# Generated by Django 4.1.3 on 2023-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Employee_Master',
            },
        ),
    ]
